name: Post Release
on:
  release:
    types: [ published ]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup vars
        id: vars
        env:
          RELEASE_REF: ${{ github.ref }}
        run: echo "::set-output name=tag::${RELEASE_REF#refs/tags/}"

      - name: Download release content
        run: |
          echo "https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/modern.tar.gz"
          wget -O modern.tar.gz "https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/modern.tar.gz"
          mkdir ./dist
          tar zxf modern.tar.gz -C ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

